# Generated by Django 4.2.1 on 2023-06-03 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Demo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=25, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('Mobile', models.CharField(max_length=15, null=True)),
                ('course', models.CharField(max_length=20, null=True)),
                ('Graduation', models.CharField(max_length=20)),
            ],
        ),
    ]
