# Generated by Django 4.2.1 on 2023-06-03 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crmApp', '0002_student_demo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_demo',
            name='Graduation',
        ),
    ]
