# Generated by Django 4.2.1 on 2023-06-03 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmApp', '0003_remove_student_demo_graduation'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_demo',
            name='gender',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
