# Generated by Django 4.2.1 on 2023-06-24 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmApp', '0005_remove_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Deleted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=25, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('Mobile', models.CharField(max_length=15, null=True)),
                ('gender', models.CharField(max_length=20, null=True)),
                ('course', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=25, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('Mobile', models.CharField(max_length=15, null=True)),
                ('gender', models.CharField(max_length=20, null=True)),
                ('course', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
