# Generated by Django 4.2.1 on 2023-07-01 10:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crmApp', '0006_student_deleted_student_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('cid', models.IntegerField(primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=20)),
                ('description', models.TextField(null=True)),
                ('image', models.ImageField(null=True, upload_to='images/')),
                ('key', models.TextField(null=True)),
                ('details', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joining_date', models.DateField()),
                ('image', models.ImageField(null=True, upload_to='images/')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crmApp.course')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Student_Deleted',
        ),
        migrations.DeleteModel(
            name='Student_Profile',
        ),
    ]
