# Generated by Django 4.2.1 on 2023-07-02 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmApp', '0009_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(choices=[('PYTHON', 'Python'), ('PYTHON FULL STACK', 'Python Full Stack'), ('JAVA', 'Java'), ('JAVA FULL STACK', 'Java Full Stack'), ('MACHINE LEARNING', 'Machine Learning'), ('AWS DEVOPS', 'AWS Devops'), ('TESTING TOOLS', 'Testing Tools'), ('POWER BI', 'Power BI'), ('TABLEAU', 'Tableau'), ('SQL SERVER', 'SQL Server'), ('SELENIUM WITH JAVA', 'Selenium with Java'), ('SELENIUM WITH PYTHON', 'Selenium with Python'), ('AZURE DATA FACTORY', 'Azure Data Factory'), ('MERN DEVELOPMENT', 'MERN Development'), ('ANGULAR JS', 'Angular Js'), ('API TESTING', 'API Testing')], default='Machine Learning', max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='course',
        ),
    ]
